[build]
  # Build command for the frontend
  command = "cd frontend && npm install && npm run build"
  # Directory to publish
  publish = "frontend/build"

[build.environment]
  # Node version
  NODE_VERSION = "18"
  # Python version for serverless functions
  PYTHON_VERSION = "3.9"

# Redirect all requests to index.html for React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# API routes for serverless functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https:;"

# Cache static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Environment variables (these will be set in Netlify dashboard)
[context.production.environment]
  REACT_APP_API_URL = "/.netlify/functions"
  REACT_APP_ENVIRONMENT = "production"

[context.deploy-preview.environment]
  REACT_APP_API_URL = "/.netlify/functions"
  REACT_APP_ENVIRONMENT = "preview"

# Functions configuration
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
